# DataSource Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/work
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  tomcat:
    max-threads: 200
  servlet:
    session:
      timeout: 86400s
      cookie:
        max-age: 86400s
  compression:
    enabled: true
    min-response-size: 2048
